/**
 * npm run draw            Make the draw (refuses if one already exists)
 * npm run draw -- --force Throw away the current draw and make a new one
 *
 * Never prints who drew whom. The result is written scrambled to
 * src/data/assignments.ts and checked before it's saved.
 */
import { existsSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { PERSON_IDS } from "../src/data/people";
import { exclusions } from "../src/data/rules";
import { generateDraw, validateDraw } from "../src/lib/draw";
import { decodeReceiver, encodeReceiver, randomSalt } from "../src/lib/secretCodec";

const target = fileURLToPath(new URL("../src/data/assignments.ts", import.meta.url));
const force = process.argv.includes("--force");

if (existsSync(target) && !force) {
  console.error("A draw already exists. Run `npm run draw -- --force` to replace it.");
  process.exit(1);
}

const ids = [...PERSON_IDS];
const cryptoRng = () => crypto.getRandomValues(new Uint32Array(1))[0]! / 2 ** 32;
const draw = generateDraw(ids, exclusions, cryptoRng);
const salt = randomSalt();
const encoded = Object.fromEntries(ids.map((g) => [g, encodeReceiver(salt, g, draw[g]!)]));

// Check the exact data we're about to save, decoded back, before writing anything.
const roundTrip = Object.fromEntries(ids.map((g) => [g, decodeReceiver(salt, g, encoded[g]!)]));
const check = validateDraw(roundTrip, ids, exclusions);
if (!check.ok) {
  console.error(`Draw failed verification (${check.errors.join(", ")}). Nothing was written.`);
  process.exit(1);
}

const lines = ids.map((g) => `  ${JSON.stringify(g)}: ${JSON.stringify(encoded[g])},`).join("\n");
writeFileSync(
  target,
  `// AUTO-GENERATED by \`npm run draw\` on ${new Date().toISOString()}. Do not edit by hand.
// The pairings are scrambled on purpose so nobody (including the host) can read them.
// To check the draw without seeing it, run \`npm test\`.

export const drawSalt = ${JSON.stringify(salt)};

export const encodedDraw: Record<string, string> = {
${lines}
};
`,
);

console.log(`✅ Draw generated and verified for ${ids.length} people.`);
