// AUTO-GENERATED by `npm run draw` on 2026-09-29T02:28:20.024Z. Do not edit by hand.
// The pairings are scrambled on purpose so nobody (including the host) can read them.
// To check the draw without seeing it, run `npm test`.

export const drawSalt = "2dfa1ac9bde58c3befb580ec8a7f4704";

export const encodedDraw: Record<string, string> = {
  "devern": "3S56T8/ZmurIRIfi03XLvIdh34x8Rnve",
  "feisha": "KgpyIzrOYyihFda8GwfVA0exqV0DMm+t",
  "eeshana": "iJVffPH8P/tvzL0smJ0Mat/Q2kr2ejhJ",
  "nathan": "Pqr34vldGfd3K8AGxOshufMwTDQm0Q/x",
  "nirvana": "rizeeaZcj0ZwA10kmnRhrwnQNwY/nqix",
  "chris-ali": "dySzuPEQ7wbtc/IC4K0OcLoZO6fO0nH4",
  "chris-alexander": "Li7zQyJDTvBzbxJeViVteqCOtgKS44zF",
  "brandon": "DbnTcrDirMPkVf8eNoF0X3Zw3D7i3+Ts",
  "dana": "Of1DahKiDqhFZlTQk3ImYTeSdjm/QOF3",
  "reyan": "Xzh630bKpzh5DrUVhD9z1puLFHv/910F",
};
