// AUTO-GENERATED by `npm run draw` on 2026-09-28T22:49:30.590Z. Do not edit by hand.
// The pairings are scrambled on purpose so nobody (including the host) can read them.
// To check the draw without seeing it, run `npm test`.

export const drawSalt = "8c473f13faf26cd893599874c4bd6235";

export const encodedDraw: Record<string, string> = {
  "devern": "JZ++ogTSoUNgxSDLBQkLQH554fNq+3wV",
  "feisha": "IKOCCLVbIC1omwKlHLVKaabtF9LFz0b5",
  "eeshana": "9kFxKpw7d2Y+M58mosvzmDdnub5wO46l",
  "nathan": "Ue3QTMrP9F91R2HnqAGa6QXXzAokNhBO",
  "nirvana": "B4jVwAfZM+DflLCEXRgpKIVbMEUsQ+UN",
  "chris-ali": "QW4lPsUu/oyfDyZjlqR6BawILf7IpTsf",
  "chris-alexander": "N0tToKn3e2OdM86FscQ456aA7T7xtF8Z",
  "brandon": "iKuSXnO5pKaED2yd0VT1IKc5AXdSD0qh",
  "dana": "1cD8O8UswwT3tEBCW7nYhFmxGippHONd",
  "reyan": "Kee6Zz1xuQMe6s7Ic7LtzmcKNtT19Rhn",
};
